#!/usr/bin/env bash
# ============================================================
# FeatureVault — EC2 Bootstrap Script
# Run once on a fresh EC2 instance after first SSH
# Usage: bash bootstrap.sh
# ============================================================
set -euo pipefail

echo "🚀 FeatureVault Bootstrap Starting..."
echo "   $(date)"
echo ""

# ── Verify running as ec2-user ────────────────────────────────
if [ "$(whoami)" != "ec2-user" ]; then
  echo "❌  Run as ec2-user, not root"
  exit 1
fi

# ── Generate secrets helper ───────────────────────────────────
generate_secret() {
  openssl rand -hex 32
}

# ── Verify Docker is running ──────────────────────────────────
if ! docker info > /dev/null 2>&1; then
  echo "❌  Docker not running. Wait for userdata to complete (check /home/ec2-user/bootstrap.log)"
  exit 1
fi
echo "✓  Docker running"

# ── Verify repo was cloned ────────────────────────────────────
if [ ! -d "/home/ec2-user/featurevault" ]; then
  echo "❌  Repo not cloned. Check userdata logs: cat /var/log/cloud-init-output.log"
  exit 1
fi
echo "✓  Repo cloned"

cd /home/ec2-user/featurevault

# ── Generate JWT keys ─────────────────────────────────────────
echo ""
echo "🔑 Generating JWT keys..."
mkdir -p apps/api/keys
openssl genrsa -out apps/api/keys/private.pem 2048
openssl rsa -in apps/api/keys/private.pem -pubout -out apps/api/keys/public.pem
chmod 600 apps/api/keys/private.pem
echo "✓  JWT keys generated"

# ── Create .env.production ────────────────────────────────────
if [ -f ".env.production" ]; then
  echo "⚠️  .env.production already exists — skipping generation"
else
  echo ""
  echo "🔐 Generating .env.production..."

  PG_PASS=$(generate_secret)
  REDIS_PASS=$(generate_secret)
  COOKIE_SECRET=$(generate_secret)

  read -p "   Enter your domain (e.g. featurevault.yourdomain.com): " DOMAIN

  cat > .env.production << ENVEOF
# Generated by bootstrap.sh on $(date)
# KEEP THIS FILE SECURE — never commit to git

POSTGRES_USER=featurevault
POSTGRES_PASSWORD=${PG_PASS}
POSTGRES_DB=featurevault

REDIS_PASSWORD=${REDIS_PASS}

COOKIE_SECRET=${COOKIE_SECRET}

WEB_URL=https://${DOMAIN}
API_URL=https://${DOMAIN}
WS_URL=wss://${DOMAIN}

# Fill in after setting up AWS SES
SMTP_HOST=email-smtp.us-east-1.amazonaws.com
SMTP_PORT=587
SMTP_USER=
SMTP_PASS=
SMTP_FROM=noreply@${DOMAIN}
ENVEOF

  echo "✓  .env.production generated"
  echo "   Secrets saved. Run 'cat .env.production' to review."
fi

# ── Nginx config ──────────────────────────────────────────────
echo ""
echo "🌐 Configuring Nginx..."
DOMAIN=$(grep WEB_URL .env.production | sed 's|.*https://||')

# Copy our nginx config
sudo cp infra/nginx/nginx.conf /etc/nginx/nginx.conf

# Replace placeholder domain
sudo sed -i "s/YOUR_DOMAIN_HERE/${DOMAIN}/g" /etc/nginx/nginx.conf

# Test config
sudo nginx -t && echo "✓  Nginx config valid"

# Create webroot for certbot
sudo mkdir -p /var/www/certbot
sudo nginx -s reload 2>/dev/null || sudo systemctl start nginx
echo "✓  Nginx started"

# ── Let's Encrypt SSL ─────────────────────────────────────────
echo ""
echo "🔒 Obtaining SSL certificate..."
echo "   Domain: ${DOMAIN}"
echo "   Make sure DNS A record points to this server first."
echo ""

read -p "   Proceed with SSL setup? (y/n): " SSL_CONFIRM
if [ "$SSL_CONFIRM" = "y" ]; then
  sudo certbot --nginx \
    -d "${DOMAIN}" \
    --non-interactive \
    --agree-tos \
    --email "admin@${DOMAIN}" \
    --redirect
  echo "✓  SSL certificate obtained"
  # Auto-renewal
  echo "0 0,12 * * * root certbot renew --quiet" | sudo tee /etc/cron.d/certbot
  echo "✓  Auto-renewal configured"
else
  echo "⚠️  Skipping SSL. Run manually: sudo certbot --nginx -d ${DOMAIN}"
fi

# ── First deploy ──────────────────────────────────────────────
echo ""
echo "🐳 Starting application..."
docker compose -f docker-compose.prod.yml pull
docker compose -f docker-compose.prod.yml build
docker compose -f docker-compose.prod.yml up -d

echo ""
echo "⏳ Waiting for services to start..."
sleep 20

# ── Run migrations ────────────────────────────────────────────
echo ""
echo "🗃  Running database migrations..."
source .env.production
docker compose -f docker-compose.prod.yml run --rm \
  -e DATABASE_URL="postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}" \
  api node apps/api/dist/lib/db/migrate.js
echo "✓  Migrations complete"

# ── Health check ──────────────────────────────────────────────
echo ""
echo "🔍 Health check..."
sleep 5
if curl -sf http://localhost:4000/health > /dev/null; then
  echo "✓  API is healthy"
else
  echo "❌  API health check failed"
  echo "   Check logs: docker compose -f docker-compose.prod.yml logs api"
fi

# ── Summary ───────────────────────────────────────────────────
echo ""
echo "╔══════════════════════════════════════════════════════╗"
echo "║         Bootstrap Complete                           ║"
echo "╠══════════════════════════════════════════════════════╣"
echo "║                                                      ║"
echo "║  Application: https://${DOMAIN}"
echo "║  API health:  https://${DOMAIN}/health"
echo "║                                                      ║"
echo "║  Useful commands:                                    ║"
echo "║  docker compose -f docker-compose.prod.yml logs -f  ║"
echo "║  docker compose -f docker-compose.prod.yml ps       ║"
echo "║                                                      ║"
echo "╚══════════════════════════════════════════════════════╝"
